# Generated by Django 2.1.7 on 2020-06-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170629_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='be_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='be_outof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fe_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fe_outof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='se_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='se_outof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='te_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='te_outof',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_outof',
        ),
        migrations.AddField(
            model_name='student',
            name='cgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='y_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='y_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Year'),
        ),
    ]
